services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # 인증 비활성화 (개발용)
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # 💥 힙 메모리 줄이기
    ports:
      - "9200:9200"  # Elasticsearch API

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.21
    container_name: kibana
    ports:
      - "5601:5601"  # Kibana UI
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
      - CSP_STRICT=false                      # ✅ CSP 완화
      - XPACK_REPORTING_ENABLE=false          # (선택) 리포팅 비활성화로 속도 향상
    depends_on:
      - elasticsearch