spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_database
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: factor2al

aws:
  sqs:
    listener:
      max-number-of-messages: 1 # 동시 처리 튜닝용
      wait-timeout : 5 # long-polling (초)
    # 로컬 개발용 큐 URL
    queue-url: ${SQS_QUEUE_URL_FOR_LOCAL}


# 로컬에서 FastAPI가 돌고 있는 호스트:포트
fastapi:
  base-url: http://localhost:8000