spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092
    consumer:
      group-id: default-consumer-group-1

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_database
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: factor2al
