spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: cloud

  datasource:
    url: jdbc:mysql://${DB_HOST:mysql_container}:3306/${DB_NAME:my_database}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:factor2al}



  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}

webhook:
  slack:
    url: ${SLACK_WEBHOOK_URL}
