spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: cloud

  datasource:
    url: jdbc:mysql://${RDS_HOST}:3306/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}



  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}

webhook:
  slack:
    url: ${SLACK_WEBHOOK_URL}

# 클러스터 내 Service 이름으로 덮어쓰기
fastapi:
  base-url: ${FASTAPI_URL}
