spring:
  application:
    name: backend
  config:
    activate:
      on-profile: default


  # ===============================
  # JPA / Hibernate
  # ===============================
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false

  # ===============================
  # kafka
  # ===============================
  kafka:
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# ===============================
# Server Port
# ===============================
server:
  port: 8080


# ===============================
# Debug mode
# ===============================
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Swagger URL
springdoc:
  api-docs:
    path: /v3/api-docs
    resolve-extensions-properties: false
  swagger-ui:
    path: /swagger-ui.html
